[package]
name = "btrust"
version = "0.1.0"
authors = ["haslersn <sebastian.hasler@gmx.net>"]
edition = "2018"

[dependencies]
blurz = "0.4"
env_logger = "0.6"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
